/** Auto-generated from Companies Job URL workbook — free careerhtml enrichment hosts. */
export const DIRECTORY_CAREER_HTML_HOST_COMPANIES: Record<string, string> = {
  '1800flowers.com': '1-800-FLOWERS.COM',
  '1stdibs.com': '1Stdibs',
  '3m.com': '3M Company',
  '53.com': 'Fifth Third Bancorp',
  'about.gitlab.com': 'GitLab Inc.',
  'about.vanguard.com': 'Vanguard Group',
  'accenture.com': 'Accenture',
  'acorns.com': 'Acorns',
  'adobe.com': 'Adobe Inc.',
  'advanceautoparts.jobs': 'Advance Auto Parts',
  'aeo.jobs': 'American Eagle Outfitters',
  'aep.com': 'American Electric Power Company  Inc.',
  'affirm.com': 'Affirm',
  'afginc.com': 'American Financial Group',
  'aflac.com': 'Aflac Incorporated',
  'aig.com': 'AIG American International Group',
  'airbnb.com': 'Airbnb',
  'airmethods.com': 'Air Methods Corporation',
  'airtransportjobs.com': 'Air Transport Services Group ATSG',
  'alaskacommunications.com': 'Alaska Communications Systems Group  Inc.',
  'albertsonscompanies.com': 'Albertsons Companies  Inc.',
  'alloy.co': 'Alloy',
  'alticeusacareers.com': 'Altice USA  Inc.',
  'amazon.jobs': 'Amazon',
  'amcnetworks.com': 'AMC Networks Inc.',
  'american-equity.com': 'American Equity Investment Life Holding Company',
  'americannational.com': 'American National Insurance Company',
  'americanstrategic.com': 'American Strategic Insurance Corp.',
  'ameriprise.com': 'Ameriprise Financial',
  'amerisourcebergen.com': 'AmerisourceBergen Corporation',
  'amg.com': 'Affiliated Managers Group  Inc.',
  'apl.com': 'American President Lines APL',
  'apple.com': 'Apple Inc.',
  'appliedmaterials.com': 'Applied Materials  Inc.',
  'archcapgroup.com': 'Arch Capital Group Ltd.',
  'aresmgmt.com': 'Ares Management',
  'asana.com': 'Asana  Inc.',
  'ascenaretail.com': 'Ascena Retail Group',
  'athene.com': 'Athene Holding Ltd.',
  'athome.com': 'At Home',
  'atlasair.com': 'Atlas Air Worldwide',
  'atlassian.com': 'Atlassian Corporation Plc',
  'atos.net': 'Atos',
  'att.jobs': 'AT&T Inc.',
  'avidxchange.com': 'AvidXchange',
  'bedbathandbeyond.jobs': 'Bed Bath & Beyond',
  'berkshirehathaway.com': 'Berkshire Hathaway',
  'berkshirehathawayenergyco.com': 'Berkshire Hathaway Energy',
  'bestbuy-jobs.com': 'Best Buy',
  'betterment.com': 'Betterment',
  'biglots.com': 'Big Lots',
  'bluestreamfiber.com': 'Blue Stream Fiber',
  'boozallen.com': 'Booz Allen Hamilton',
  'box.com': 'Box  Inc.',
  'brex.com': 'Brex',
  'broadcom.com': 'Broadcom Inc.',
  'burlingtonstores.jobs': 'Burlington Stores',
  'buzzfeed.com': 'BuzzFeed  Inc.',
  'cadencebankcareers.com': 'Cadence Bank',
  'capgemini.com': 'Capgemini',
  'capitalonecareers.com': 'Capital One Financial Corporation',
  'careers-inc.nttdata.com': 'NTT DATA',
  'careers.7-eleven.com': '7-Eleven  Inc.',
  'careers.academy.com': 'Academy Sports  Outdoors',
  'careers.acadiahealthcare.com': 'Acadia Healthcare Company  Inc.',
  'careers.airbnb.com': 'Airbnb  Inc.',
  'careers.alaskaair.com': 'Alaska Airlines',
  'careers.allegiantair.com': 'Allegiant Air',
  'careers.allianz.com': 'Allianz Life Insurance Company of North America',
  'careers.allstate.com': 'Allstate Corporation',
  'careers.americancentury.com': 'American Century Investments',
  'careers.americanexpress.com': 'American Express Company',
  'careers.ameriprise.com': 'Ameriprise Financial',
  'careers.amfam.com': 'American Family Insurance Group',
  'careers.antheminc.com': 'Anthem  Inc.',
  'careers.auto-owners.com': 'Auto-Owners Insurance',
  'careers.autozone.com': 'AutoZone',
  'careers.bankofamerica.com': 'Bank of America',
  'careers.bjs.com': 'BJ\'s Wholesale Club',
  'careers.blackrock.com': 'BlackRock',
  'careers.bloomberg.com': 'Bloomberg L.P.',
  'careers.buildabear.com': 'Build-A-Bear Workshop',
  'careers.cerner.com': 'Cerner Corporation',
  'careers.changehealthcare.com': 'Change Healthcare Holdings  Inc.',
  'careers.chewy.com': 'Chewy',
  'careers.chubb.com': 'Chubb Limited',
  'careers.cognizant.com': 'Cognizant',
  'careers.comerica.com': 'Comerica Incorporated',
  'careers.coned.com': 'Con Edison  Inc.',
  'careers.conocophillips.com': 'ConocoPhillips',
  'careers.cummins.com': 'Cummins Inc.',
  'careers.davita.com': 'DaVita Inc.',
  'careers.dickssportinggoods.com': 'DICK\'S Sporting Goods',
  'careers.dish.com': 'DISH Network Corporation',
  'careers.dollargeneral.com': 'Dollar General',
  'careers.dominionenergy.com': 'Dominion Energy  Inc.',
  'careers.eatonvance.com': 'Eaton Vance',
  'careers.ebayinc.com': 'eBay',
  'careers.edwardjones.com': 'Edward Jones',
  'careers.enterpriseproducts.com': 'Enterprise Products Partners L.P.',
  'careers.federatedinvestors.com': 'Federated Hermes  Inc.',
  'careers.fedex.com': 'FedEx Corporation',
  'careers.fglife.com': 'Fidelity & Guaranty Life',
  'careers.frostbank.com': 'Frost Bank Corporation',
  'careers.gamestop.com': 'GameStop',
  'careers.genworth.com': 'Genworth Financial',
  'careers.google.com': 'Google Alphabet Inc.',
  'careers.hcahealthcare.com': 'HCA Healthcare  Inc.',
  'careers.homedepot.com': 'The Home Depot',
  'careers.hpe.com': 'Hewlett Packard Enterprise Company',
  'careers.hulu.com': 'Hulu  LLC',
  'careers.info.riteaid.com': 'Rite Aid Corporation',
  'careers.instacart.com': 'Instacart',
  'careers.intuit.com': 'Intuit Inc.',
  'careers.invesco.com': 'Invesco Ltd.',
  'careers.itw.com': 'Illinois Tool Works Inc.',
  'careers.jetblue.com': 'JetBlue Airways',
  'careers.jpmorgan.com': 'JPMorgan Chase & Co.',
  'careers.key.com': 'KeyCorp',
  'careers.kohls.com': 'Kohl\'s',
  'careers.lb.com': 'L Brands',
  'careers.libertylatinamerica.com': 'Cable & Wireless Communications Limited C&W Communications',
  'careers.linkedin.com': 'LinkedIn Microsoft',
  'careers.magellanhealth.com': 'Magellan Health  Inc.',
  'careers.mcdonalds.com': 'McDonald\'s Corporation',
  'careers.mckesson.com': 'McKesson Corporation',
  'careers.metronetinc.com': 'MetroNet  Inc.',
  'careers.microsoft.com': 'Microsoft',
  'careers.nationwide.com': 'Nationwide Mutual Insurance Company',
  'careers.nordstrom.com': 'Nordstrom',
  'careers.northerntrust.com': 'Northern Trust Corporation',
  'careers.parker.com': 'Parker-Hannifin Corporation',
  'careers.petco.com': 'Petco',
  'careers.pinterest.com': 'Pinterest  Inc.',
  'careers.questdiagnostics.com': 'Quest Diagnostics Incorporated',
  'careers.robinhood.com': 'Robinhood',
  'careers.shentel.com': 'Shentel Shenandoah Telecommunications Company',
  'careers.slb.com': 'Schlumberger Limited',
  'careers.snap.com': 'Snap Inc.',
  'careers.southwestair.com': 'Southwest Airlines',
  'careers.spglobal.com': 'S&P Global Inc.',
  'careers.spirit.com': 'Spirit Airlines',
  'careers.squareup.com': 'Square  Inc.',
  'careers.statestreet.com': 'State Street Corporation',
  'careers.synovus.com': 'Synovus Financial Corp',
  'careers.teamhealth.com': 'TeamHealth Holdings  Inc.',
  'careers.ti.com': 'Texas Instruments Incorporated',
  'careers.tiaa.org': 'TIAA',
  'careers.tiktok.com': 'TikTok',
  'careers.tractorsupply.com': 'Tractor Supply Company',
  'careers.travelers.com': 'Travelers Companies Inc.',
  'careers.truist.com': 'Truist Financial Corporation',
  'careers.twitter.com': 'Twitter  Inc.',
  'careers.ulta.com': 'Ulta Beauty',
  'careers.unitedhealthgroup.com': 'UnitedHealth Group',
  'careers.unity.com': 'Unity Technologies SF',
  'careers.vonage.com': 'Vonage Holdings Corp.',
  'careers.waddell.com': 'Waddell & Reed Financial  Inc.',
  'careers.walmart.com': 'Walmart',
  'careers.werner.com': 'Werner Enterprises',
  'careers.westernsouthernlife.com': 'Western & Southern Financial Group',
  'careers.wipro.com': 'Wipro Limited',
  'careers.yrcw.com': 'YRC Worldwide Inc.',
  'careers.zionsbank.com': 'Zions Bancorporation',
  'cbscorporation.jobs': 'CBS Corporation',
  'cgi.com': 'CGI Inc.',
  'cheniere.hua.hrsmart.com': 'Cheniere Energy  Inc.',
  'chevron.com': 'Chevron Corporation',
  'chrobinson.com': 'C.H. Robinson Worldwide  Inc.',
  'cincinnatibell.com': 'Cincinnati Bell Inc.',
  'circle.com': 'Circle',
  'cititrends.com': 'Citi Trends',
  'cma-cgm.com': 'CMA CGM Group',
  'cmegroup.com': 'CME Group Inc.',
  'consolidated.com': 'Consolidated Communications Holdings  Inc.',
  'containerstore.com': 'The Container Store',
  'corning.com': 'Corning Incorporated',
  'corporate.abercrombie.com': 'Abercrombie & Fitch',
  'corporate.discovery.com': 'Discovery  Inc.',
  'corporate.exxonmobil.com': 'Exxon Mobil Corporation',
  'corporate.ford.com': 'Ford Motor Company',
  'corporate.gapinc.com': 'Gap Inc.',
  'corporate.kohls.com': 'Kohl\'s Corporation',
  'corporate.oreillyauto.com': 'O\'Reilly Automotive  Inc.',
  'corporate.partycity.com': 'Party City',
  'corporate.target.com': 'Target Corporation',
  'corporate.univision.com': 'Univision Communications Inc.',
  'costco.com': 'Costco Wholesale',
  'cpr.ca': 'Canadian Pacific Railway Limited',
  'crowley.com': 'Crowley Maritime Corporation',
  'csx.com': 'CSX Corporation',
  'current.com': 'Current',
  'deere.com': 'Deere & Company',
  'deltajobs.net': 'Delta Air Lines',
  'designerbrands.com': 'Designer Brands',
  'devonenergy.com': 'Devon Energy Corporation',
  'dignityhealthcareers.org': 'Dignity Health',
  'docusign.com': 'DocuSign  Inc.',
  'dollartree.com': 'Dollar Tree',
  'doordash.com': 'DoorDash',
  'dpdhl.jobs': 'DHL',
  'drive4swift.com': 'Swift Transportation Company',
  'dropbox.com': 'Dropbox  Inc.',
  'duke-energy.com': 'Duke Energy Corporation',
  'dxc.technology': 'DXC Technology',
  'eaton.com': 'Eaton Corporation plc',
  'emerson.com': 'Emerson Electric Co.',
  'endeavorair.com': 'Endeavor Air',
  'eogresources.com': 'EOG Resources  Inc.',
  'epam.com': 'EPAM Systems',
  'eqt.com': 'EQT Corporation',
  'erieinsurance.com': 'Erie Insurance Group',
  'etrade.com': 'ETRADE',
  'etsy.com': 'Etsy',
  'evergreen-line.com': 'Evergreen Line',
  'evhc.net': 'Envision Healthcare Corporation',
  'exeloncorp.com': 'Exelon Corporation',
  'expeditors.com': 'Expeditors International of Washington  Inc.',
  'ey.com': 'Ernst & Young EY',
  'facebook.com': 'Facebook Meta Platforms  Inc.',
  'fbfs.com': 'FBL Financial Group  Inc.',
  'fidelitycommunications.com': 'Fidelity Communications Co.',
  'firstcitizens.com': 'First Citizens BancShares  Inc.',
  'firsthorizon.com': 'First Horizon Corporation',
  'firstrepublic.com': 'First Republic Bank',
  'flyfrontiercareers.silkroad.com': 'Frontier Airlines',
  'footlocker-inc.com': 'Foot Locker',
  'foxcareers.com': 'Fox Corporation',
  'francescas.com': 'Francesca\'s',
  'franklinresources.com': 'Franklin Resources  Inc.',
  'franklintempletoncareers.com': 'Franklin Templeton Investments',
  'frontier.com': 'Frontier Communications Corporation',
  'genesiscareers.jobs.net': 'Genesis Healthcare Inc.',
  'getdivvy.com': 'Divvy',
  'github.com': 'GitHub  Inc.',
  'globalatlantic.com': 'Global Atlantic Financial Group',
  'goldmansachs.com': 'Goldman Sachs Group Inc.',
  'gtt.net': 'GTT Communications  Inc.',
  'hanover.com': 'The Hanover Insurance Group',
  'hapag-lloyd.com': 'Hapag-Lloyd AG',
  'hawaiianairlines.com': 'Hawaiian Airlines',
  'hawaiiantel.com': 'Hawaiian Telcom Holdco  Inc.',
  'hcltech.com': 'HCL Technologies',
  'hearst.com': 'Hearst Corporation',
  'hexaware.com': 'Hexaware Technologies',
  'hibbett.com': 'Hibbett Sports',
  'hippo.com': 'Hippo Insurance',
  'hitachiconsulting.com': 'Hitachi Consulting',
  'honeywell.com': 'Honeywell International Inc.',
  'horacemann.com': 'Horace Mann Educators Corporation',
  'humana.com': 'Humana Inc.',
  'huntington.com': 'Huntington Bancshares Incorporated',
  'ibm.com': 'IBM',
  'independent-bank.com': 'Independent Bank Group  Inc.',
  'info.lululemon.com': 'Lululemon',
  'infosys.com': 'Infosys',
  'jbhunt.com': 'J.B. Hunt Transport Services  Inc.',
  'jobs-ups.com': 'UPS United Parcel Service',
  'jobs.aa.com': 'American Airlines',
  'jobs.amedisys.com': 'Amedisys  Inc.',
  'jobs.apple.com': 'Apple Inc.',
  'jobs.ascension.org': 'Ascension Health Alliance',
  'jobs.assurant.com': 'Assurant  Inc.',
  'jobs.bakerhughes.com': 'Baker Hughes Company',
  'jobs.bedbathandbeyond.com': 'Bed Bath & Beyond Inc.',
  'jobs.bmoharris.com': 'BMO Harris Bank N.A.',
  'jobs.bnsf.com': 'BNSF Railway',
  'jobs.bnymellon.com': 'The Bank of New York Mellon Corporation',
  'jobs.boeing.com': 'Boeing Company',
  'jobs.brookdale.com': 'Brookdale Senior Living Inc.',
  'jobs.capitalgroup.com': 'Capital Group',
  'jobs.cardinalhealth.com': 'Cardinal Health  Inc.',
  'jobs.centene.com': 'Centene Corporation',
  'jobs.chemed.com': 'Chemed Corporation',
  'jobs.chs.net': 'Community Health Systems  Inc.',
  'jobs.cigna.com': 'Cigna Corporation',
  'jobs.cisco.com': 'Cisco Systems  Inc.',
  'jobs.citi.com': 'Citigroup Inc.',
  'jobs.citizensbank.com': 'Citizens Financial Group  Inc.',
  'jobs.cn.ca': 'Canadian National Railway Company',
  'jobs.comcast.com': 'Comcast Corporation',
  'jobs.coxenterprises.com': 'Cox Communications  Inc.',
  'jobs.cvshealth.com': 'CVS Health Corporation',
  'jobs.dell.com': 'Dell Technologies',
  'jobs.disneycareers.com': 'Walt Disney Company',
  'jobs.encompasshealth.com': 'Encompass Health Corporation',
  'jobs.espncareers.com': 'ESPN',
  'jobs.express.com': 'Express',
  'jobs.farmersinsurance.com': 'Farmers Insurance Group',
  'jobs.fidelity.com': 'Fidelity Investments',
  'jobs.fmcna.com': 'Fresenius Medical Care AG & Co. KGaA',
  'jobs.gecareers.com': 'General Electric Company',
  'jobs.genesco.com': 'Genesco',
  'jobs.groupon.com': 'Groupon',
  'jobs.hanger.com': 'Hanger  Inc.',
  'jobs.hcsc.com': 'Health Care Service Corporation HCSC',
  'jobs.hsn.com': 'HSN Home Shopping Network',
  'jobs.intel.com': 'Intel Corporation',
  'jobs.jcp.com': 'JCPenney',
  'jobs.jobvite.com': 'Lions Gate Entertainment Corp.',
  'jobs.kindredathome.com': 'Sun Healthcare Group  Inc.',
  'jobs.kroger.com': 'The Kroger Co.',
  'jobs.labcorp.com': 'Laboratory Corporation of America Holdings',
  'jobs.lhcgroup.com': 'LHC Group  Inc.',
  'jobs.libertyglobal.com': 'Liberty Broadband Corporation',
  'jobs.libertymutualgroup.com': 'Liberty Mutual Insurance Group',
  'jobs.lowes.com': 'Lowe\'s',
  'jobs.lumen.com': 'CenturyLink  Inc. now Lumen Technologies',
  'jobs.metlife.com': 'MetLife  Inc.',
  'jobs.molinahealthcare.com': 'Molina Healthcare  Inc.',
  'jobs.nationalgeneral.com': 'National General Holdings Corp.',
  'jobs.netflix.com': 'Netflix  Inc.',
  'jobs.newyorklife.com': 'New York Life Insurance Company',
  'jobs.officedepot.com': 'Office Depot',
  'jobs.pnc.com': 'PNC Financial Services Group  Inc.',
  'jobs.publix.com': 'Publix Super Markets  Inc.',
  'jobs.qurateretailgroup.com': 'Qurate Retail Group',
  'jobs.rh.com': 'RH Restoration Hardware',
  'jobs.riteaid.com': 'Rite Aid',
  'jobs.rossstores.com': 'Ross Stores',
  'jobs.sallybeauty.com': 'Sally Beauty Holdings',
  'jobs.schwabjobs.com': 'Charles Schwab Corporation',
  'jobs.selectmedical.com': 'Select Medical Corporation',
  'jobs.spectrum.com': 'Charter Communications  Inc.',
  'jobs.synchrony.com': 'Synchrony Financial',
  'jobs.tailoredbrands.com': 'Tailored Brands',
  'jobs.target.com': 'Target',
  'jobs.td.com': 'TD Bank  N.A.',
  'jobs.tenethealth.com': 'Tenet Healthcare Corporation',
  'jobs.tjx.com': 'TJX Companies',
  'jobs.truist.com': 'SunTrust Banks  Inc.',
  'jobs.uhsinc.com': 'Universal Health Services  Inc.',
  'jobs.united.com': 'United Airlines',
  'jobs.walgreens.com': 'Walgreens Boots Alliance  Inc.',
  'jobs.wowway.com': 'WOW Internet  Cable & Phone',
  'jobs.xpo.com': 'XPO Logistics',
  'jobs2.deloitte.com': 'Deloitte',
  'joinroot.com': 'Root Insurance',
  'kabbage.com': 'Kabbage',
  'kaiserpermanentejobs.org': 'Kaiser Permanente',
  'kalittaair.com': 'Kalitta Air',
  'kcsouthern.com': 'Kansas City Southern Railway',
  'kemper.com': 'Kemper Corporation',
  'kindermorgan.com': 'Kinder Morgan  Inc.',
  'kindredhealthcare.com': 'Kindred Healthcare  LLC',
  'klarna.com': 'Klarna',
  'landsend.com': 'Lands\' End',
  'landstar.com': 'Landstar System  Inc.',
  'lazard.com': 'Lazard Ltd.',
  'lemonade.com': 'Lemonade',
  'lendingclub.com': 'LendingClub',
  'levistrauss.com': 'Levi Strauss & Co.',
  'lifepointhealth.jobs.net': 'LifePoint Health  Inc.',
  'lingotalk.com': 'Lingo Communications',
  'lla.com': 'Liberty Latin America Ltd.',
  'lntinfotech.com': 'LTI L&T Infotech',
  'lockheedmartinjobs.com': 'Lockheed Martin Corporation',
  'lumosnetworks.com': 'Lumos Networks Corp.',
  'lyft.com': 'Lyft  Inc.',
  'lynden.com': 'Alaska Marine Lines',
  'macysjobs.com': 'Macy\'s',
  'maersk.com': 'Maersk Line',
  'marathonpetroleum.com': 'Marathon Petroleum Corporation',
  'markel.com': 'Markel Corporation',
  'matson.com': 'Matson  Inc.',
  'mgic.com': 'MGIC Investment Corporation',
  'michaels.com': 'Michaels',
  'micron.com': 'Micron Technology  Inc.',
  'midco.com': 'Midco Midcontinent Communications',
  'mindtree.com': 'Mindtree',
  'mongodb.com': 'MongoDB  Inc.',
  'moodys.com': 'Moody\'s Corporation',
  'morganstanley.com': 'Morgan Stanley',
  'mphasis.com': 'Mphasis',
  'msci.com': 'MSCI Inc.',
  'nationalgrid.com': 'National Grid plc',
  'nbcunicareers.com': 'NBCUniversal Media  LLC',
  'nexteraenergy.com': 'NextEra Energy  Inc.',
  'nomuraholdings.com': 'Nomura Holdings',
  'northropgrumman.com': 'Northrop Grumman Corporation',
  'nscorp.com': 'Norfolk Southern Corporation',
  'nutanix.com': 'Nutanix  Inc.',
  'nvidia.com': 'NVIDIA Corporation',
  'odfl.com': 'Old Dominion Freight Line  Inc.',
  'okta.com': 'Okta  Inc.',
  'ondeck.com': 'OnDeck',
  'oneok.com': 'ONEOK  Inc.',
  'oocl.com': 'OOCL Orient Overseas Container Line',
  'oracle.com': 'Oracle Corporation',
  'otelco.com': 'Otelco Inc.',
  'overstock.com': 'Overstock.com',
  'oxy.com': 'Occidental Petroleum Corporation',
  'ozk.com': 'Bank OZK',
  'pacificlife.com': 'Pacific Life',
  'palantir.com': 'Palantir Technologies Inc.',
  'payoneer.com': 'Payoneer',
  'paypal.com': 'PayPal Holdings  Inc.',
  'persistent.com': 'Persistent Systems',
  'personalcapital.com': 'Personal Capital',
  'phillips66.com': 'Phillips 66',
  'policygenius.com': 'Policygenius',
  'primerica.com': 'Primerica  Inc.',
  'principal.com': 'The Principal Financial Group',
  'protective.com': 'Protective Life Corporation',
  'prudential.com': 'Prudential Financial',
  'pwc.com': 'PricewaterhouseCoopers PwC',
  'qualcomm.com': 'Qualcomm Incorporated',
  'ramp.com': 'Ramp',
  'rapyd.net': 'Rapyd',
  'raymondjames.com': 'Raymond James Financial',
  'redditinc.com': 'Reddit  Inc.',
  'regions.com': 'Regions Financial Corporation',
  'revolvegroup.com': 'Revolve Group',
  'ringcentral.com': 'RingCentral  Inc.',
  'rjetcareers.jobs': 'Republic Airways',
  'rlicorp.com': 'RLI Corp.',
  'ryder.com': 'Ryder System  Inc.',
  'salesforce.com': 'Salesforce.com  Inc.',
  'santanderconsumerusa.com': 'Santander Consumer USA Holdings Inc.',
  'schneiderjobs.com': 'Schneider National  Inc.',
  'schwabjobs.com': 'Charles Schwab & Co.  Inc.',
  'search-careers.gm.com': 'General Motors Company',
  'segra.com': 'Segra',
  'servicenow.com': 'ServiceNow  Inc.',
  'shoecarnival.com': 'Shoe Carnival',
  'signetjewelers.com': 'Signet Jewelers',
  'skywest.com': 'SkyWest Airlines',
  'slack.com': 'Slack Technologies  Inc.',
  'snap.com': 'Snap Inc.',
  'sneakerjobs.com': 'Foot Locker  Inc.',
  'socure.com': 'Socure',
  'sonypicturesjobs.com': 'Sony Corporation of America',
  'southerncompany.com': 'Southern Company',
  'sparklight.com': 'Cable One  Inc. now Sparklight',
  'spotifyjobs.com': 'Spotify Technology S.A.',
  'squarespace.com': 'SquareSpace  Inc.',
  'stash.com': 'Stash',
  'statefarm.com': 'State Farm',
  'stitchfix.com': 'Stitch Fix',
  'stripe.com': 'Stripe  Inc.',
  't-mobile.com': 'T-Mobile US  Inc.',
  'tcs.com': 'Tata Consultancy Services TCS',
  'tdameritrade.com': 'TD Ameritrade',
  'tdstelecom.com': 'TDS Telecommunications LLC',
  'techmahindra.com': 'Tech Mahindra',
  'tesla.com': 'Tesla  Inc.',
  'thehartford.com': 'Hartford Financial Services Group',
  'therealreal.com': 'The RealReal',
  'timewarner.com': 'Time Warner Inc.',
  'toteinc.com': 'TOTE Maritime',
  'tractorsupply.jobs': 'Tractor Supply Company',
  'troweprice.com': 'T. Rowe Price Group  Inc.',
  'twilio.com': 'Twilio Inc.',
  'uber.com': 'Uber Technologies  Inc.',
  'ubs.com': 'UBS Group AG',
  'umpquabankcareers.com': 'Umpqua Holdings Corporation',
  'uniti.com': 'Uniti Group Inc.',
  'unum.com': 'Unum Group',
  'up.jobs': 'Union Pacific Railroad',
  'usaajobs.com': 'USAA',
  'usbank.com': 'U.S. Bancorp',
  'uscellular.jobs': 'United States Cellular Corporation',
  'utc.com': 'United Technologies Corporation',
  'valero.com': 'Valero Energy Corporation',
  'varomoney.com': 'Varo Bank',
  'verizon.com': 'Verizon Communications Inc.',
  'verizonmedia.com': 'Yahoo Verizon Media',
  'viacomcbs.careers': 'ViacomCBS Inc.',
  'virtu.com': 'Virtu Financial',
  'virtusa.com': 'Virtusa',
  'voya.com': 'Voya Financial',
  'waltdisneystudios.com': 'The Walt Disney Studios',
  'warnermediacareers.com': 'AT&T Inc. WarnerMedia',
  'wavebroadband.com': 'Wave Broadband',
  'wayfair.com': 'Wayfair',
  'websterbank.com': 'Webster Financial Corporation',
  'wellsfargojobs.com': 'Wells Fargo & Company',
  'williams-sonomainc.com': 'Williams-Sonoma',
  'williams.com': 'Williams Companies  Inc.',
  'windstream.com': 'Windstream Holdings  Inc.',
  'wmg.com': 'Warner Music Group',
  'workday.com': 'Workday  Inc.',
  'www3.mtb.com': 'M&T Bank Corporation',
  'zensar.com': 'Zensar Technologies',
  'ziplyfiber.com': 'Ziply Fiber',
  'zoom.us': 'Zoom Video Communications  Inc.',
  'zscaler.com': 'Zscaler  Inc.',
  'zumiez.com': 'Zumiez',
};
